OZ-Coding-School/oz_externship_be_01

resources/scripts/test.sh
=> test.sh에 장고 env export 추가

apps/users/apps.py, apps/users/models.py, apps/users/tests.py
=> add users app

apps/qna/serializers/questions_serializers.py, apps/qna/urls.py, apps/qna/views/questions_views.py, config/urls.py
- 관련 이슈 번호: x
- 작업 요약: questions에 관한 mock api 작성 했습니다.
post 나 patch에서 swagger 테스트 시 허용되지 않는다고 뜨는데 정확한 이유를 잘 모르겠습니다.
알려주시면 감사하겠습니다.
그래도 저도 그동안 열심히 찾고 알게 된다면 수정하고 다시 커밋하겠습니다!
=> ✨ feat: qna/questions mockapi 추가

apps/users/models/withdrawals.py, apps/users/serializers/withdrawal_serializers.py, apps/users/urls.py, apps/users/views/withdrawal_views.py, config/urls.py
- 작업 요약: 회원 탈퇴 및 복구 mock api
- 회원 탈퇴용 UserDeleteView 및 복구용 UserRestoreView 구현
=> ✨  feat     : 회원 탈퇴 및 복구 mock api 기능추가

apps/users/serializers/profile_serializers.py, apps/users/urls.py, apps/users/views/profile_views.py
- 작업 요약: 내정보 조회 및 수정 mock api 기능추가
- 내정보 조회 및 수정 뷰 시리얼라이저 구현
=> ✨  feat     : 내정보 조회 및 수정 mock api 기능추가

apps/users/serializers/find_account_serializers.py, apps/users/urls.py, apps/users/views/find_account_views.py
이메일 찾기, 비밀번호 찾기 views, serializers 구현
- 작업 요약: 이메일 찾기, 비밀번호 찾기 기능추가
=> ✨  feat     : 이메일 찾기, 비밀번호 찾기 기능추가

apps/users/serializers/admin_dashboard_serializers.py, apps/users/urls.py, apps/users/views/admin_dashboard_views.py
수강생 전환, 회원가입, 회원 탈퇴, 탈퇴 사유 추세 그래프 mock api 구현
- 수강생 전환 추이 그래프 mock api 구현
- 회원가입 추이 그래프 mock api 구현
- 회원 탈퇴, 탈퇴 사유 추세 그래프 mock api 구현
=> ✨ feat: 어드민 유저 대시보드 mock api 구현

apps/community/views/admin/category_views.py
=> ♻️ refactor: 정렬 코드 추가

apps/courses/serializers/subject_serializers.py, apps/courses/views/subject_views.py
- 작업 요약: 어드민 과목 관리 기능 추가
- 페이지네이션 기능 추가
- 이미지파일 인아웃 형태 지정 
- 주석 제거 및 멀티파트 파서 적용
=>  ✨ feat     : add admin subject functions

apps/qna/permissions.py, apps/qna/serializers/answers_serializers.py, apps/qna/views/answers_views.py
- 작업 요약: 질의응답 답변 관련 API 작성
우리 db에는 이미지 url만 저장하고 실제 이미지 파일은 다른곳에 저장하는데, (이렇게 이해한게 맞나요??)
이 부분은 아직 구현하지 않았다.
=> ✨ feat: 답변 생성,수정, 채택, 댓글 api 작성

apps/community/views/admin/category_views.py
=> ✨ feat: 카테고리 등록 API 제작

apps/users/serializers/auth/email_login.py, apps/users/urls.py, apps/users/views/auth/email_login.py, config/settings/base.py
2. 변경 또는 추가사항을 아래에 간략하게 작성하세요 ( 필수 )
- 이메일 로그인 기능 구현. access token, refresh token과 사용자 정보 응답.
=> ✨ feat: 이메일 로그인 기능.

apps/qna/serializers/answers_serializers.py, apps/qna/views/answers_views.py
=> ♻️ refactor : 이미지 처리 로직 수정

apps/qna/serializers/admin_serializers.py, apps/qna/views/admin_views.py
- 작업 요약: 카테고리 등록/삭제 기능구현
-qna/views.py
-qna/serializers.py
카테고리 등록 및 삭제 기능구현
=>  ✨ feat: 카테고리 등록/삭제 기능 구현

apps/users/urls.py, apps/users/utils/kakao.py, apps/users/views/auth/social_login.py
- utils/kakao.py 생성하여 토큰, 유저정보 가져오는 함수 정의
- 카카오 로그인 api 구현
- 백엔드 내에서 테스트를 위한 콜백 api
=> ✨ feat: 카카오 소셜 로그인 api 구현

apps/courses/models.py
=> Course init 메서드 수정

apps/community/serializers/category_serializers.py, apps/community/views/admin/category_views.py
=> ✨ feat: 카테고리 게시글 ON/OFF API 추가 !!

apps/community/views/admin/category_views.py
=> ♻️ refactor: tags 추가 !!

apps/courses/models.py
=> [Hotfix] Generation 모델 init메서드 긴급수정

apps/users/views/admin_user_views.py
- 작업 요약: 어드민 전용 회원 목록 조회 api 구현
- 페이지네이션 구현
- 필터 기능 구현
=> ✨ feat: 어드민 전용 회원 목록 조회 api 구현

apps/tests/models.py
- 관련 이슈 번호: 없음
- 작업 요약: 쪽지시험 모델의 enum(문제유형, 배포상태)을 TextChoices로 리팩토링하여 유지보수성과 코드 일관성 개선
- [] TestQuestion 모델의 QUESTION_TYPE_CHOICES 전역 상수를 제거하고 QuestionType TextChoices 클래스 변경
- [] TestDeployment 모델의 TEST_STATUS_CHOICES 전역 상수를 제거하고 TestStatus TextChoices 클래스 변경
- [] 각 모델의 type/status 필드에 choices 연결 방식을 TextChoices 기반 통일
- 없음
- TextChoices로 리팩토링하여 문제유형, 배포상태를 모델 내부에서 명확하게 관리할 수 있게 되었습니다.
- enum 값은 기존과 동일하므로 DB 데이터와 호환성 문제가 발생하지 않습니다.
- 이번 변경은 코드 구조만 개선되었으며, Django가 감지할 만한 스키마 변경이 없으므로 마이그레이션은 생성되지 않았습니다.
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> Feature/test hotfixmodel lsi ( 쪽지시험 모델 리팩토링 )

apps/users/serializers/admin_user_serializers.py, apps/users/views/admin_user_views.py
- 작업 요약: 상세 조회 api 구현
- 상세 조회 시리얼라이저 정의
- 권한에 따라 반환 항목이 달라지게 구현
=> ✨ feat: 어드민 회원 상세 조회 api 구현

apps/qna/error_messages.py, apps/qna/views/answers_views.py
=> ♻️ refactor : response에 사용되는 메세지들 분리 (급한거 아니라서 천천히 봐주십쇼!)

apps/users/serializers/admin_enrollments_list_serializers.py, apps/users/urls.py, apps/users/views/admin_enrollments_list_views.py
- 관리자 모두 전체 수강신청 데이터를 조회
- 수강생 등록 신청 목록 조회 View 구현
=> ✨  feat   :(Admin) 수강생 등록 신청 현황 목록 조회 API

apps/tests/serializers/test_question_serializers.py, apps/tests/urls.py, apps/tests/views/admin_testquestion_views.py
=>  ✨ feat     : 쪽지시험문제수정 기능 추가

apps/users/serializers/admin_dashboard_serializers.py, apps/users/views/admin_dashboard_views.py
- 관련 이슈 번호: 없음
- 작업 요약: 수강생 전환 추이 분석 차트 api 구현
- 유저별 최초 수강신청 승인만 추출해 집계할 수 있도록 구현
=> ✨ feat: 수강생 전환 추이 분석 차트 api 구현

apps/users/serializers/admin_enrollments_approve_serializers.py, apps/users/views/admin_enrollments_approve_views.py
- 관련 이슈 번호: 없음
- 작업 요약: 누락 변수명 수정
- 시리얼라이저명 명확하게 변경
- 누락된 변수명 수정으로 테스트 오류 해결
=> 🐛 fix: enrollment_request_ids 변수 누락으로 인한 테스트 오류 해결

apps/users/views/admin_dashboard_views.py
- 관련 이슈 번호: 없음
- 작업 요약: 회원 탈퇴 추세 구현
- 월별, 년별로 나뉘어 확인할 수 있게 구현
=> ✨ feat: 어드민 회원 탈퇴 추세 대시보드 api 구현

apps/tests/serializers/test_serializers.py
- 관련 이슈 번호: 없음
- 작업 요약: 쪽지시험 상세조회 API 응답에 썸네일 이미지 URL과 문제 해설 필드 추가
없음
- 프론트 요청사항에 따라 추가하였으며, 향후 요구사항 정의서 수정 권한이 부여되면 해당 변경사항도 반영할 예정입니다.
=> Feature/test hotfixdetail lsi(쪽지시험 상세조회 응답 필드 추가)

apps/users/serializers/admin_user_serializers.py, apps/users/views/admin_user_views.py
- 관련 이슈 번호: 없음
- 작업 요약: 회원 수정 api 구현
- S3Uploader를 이용해 전용 시리얼라이저 작성
=> ✨ feat: 어드민 회원 수정 api 구현

apps/users/serializers/auth/find_email_phone_verification.py, apps/users/tasks.py, apps/users/urls.py, apps/users/utils/email_masking_utils.py, apps/users/utils/redis_utils.py, apps/users/views/auth/find_email_phone_verification.py, apps/users/views/find_account_views.py
- 이메일 찾기/비밀번호 재설정 - 인증코드 발송 API 실제 구현
- email_masking_utils.py에 mask_email() 함수 추가
- redis_utils.py에 reset: 관련 함수 (store/get/verify/delete) 정리
=> ✨  feat   :이메일 찾기, 비밀번호 찾기 API

apps/users/serializers/auth/phone_auth.py
- 실제로 인증이 실패했는데 인증 성공으로 넘어가는 문제 해결
=> ♻️refactor: 회원가입용 휴대폰 인증 로직 개선

apps/users/serializers/auth/signup.py, apps/users/urls.py, apps/users/views/auth/signup.py
=>  ✨  feat   :회원가입용 닉네임 중복확인 api 추가

apps/community/views/admin/notice_views.py, apps/community/views/admin/post_views.py
- 작업 요약: admin post 스키마 태그 오타 수정
=> ♻️refactor: 태그 오타 수정

README.md
=> 📝 docs : 3팀 qna 파트 리드미 작성

apps/users/serializers/auth/signup.py, apps/users/views/auth/signup.py
2. 변경 또는 추가사항을 아래에 간략하게 작성하세요 ( 필수 ) 회원가입시 이미지 파일을 S3에 저장하게 수정.
- 관련 이슈 번호: 없음
- 작업 요약: 회원가입시 이미지파일 추가.
=> ✨ feat: 회원가입시 이미지파일 업로드 기능 추가.

apps/tests/serializers/test_deployment_serializers.py
- 관련 이슈 번호: #
- 작업 요약: 문제 점수 누락 시 None 대신 0 처리하여 500 오류 방지
=> [Fix/test user list gej] works: 문제 점수 누락 시 500 오류 방지 수정

apps/tests/views/admin_test_views.py
- 관련 이슈 번호: 없음
- 작업 요약: 프론트 요청으로 인해 쪽지시험 목록조회 API 정렬 기능 확장 (`-created_at`, `title` 등 지원)
- [] ordering 파라미터에 Django ORM 형식 정렬 옵션 적용 (`-created_at`, `created_at`, `title`, `-title`)
- [] 기존 `recent`, `alphabetical` 방식 제거하고 더 유연한 정렬 방식 도입
- [] ordering 파라미터가 허용된 필드 내에서만 작동하도록 안전 처리
없음
- API 명세서 정렬 옵션 항목 최신화 완료
- 정렬기준 파라미터 요청 값 프론트와 공유 완료
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)
=> Feature/test hotfixlist lsi ( 쪽지시험 목록조회 API 정렬 옵션 개선 (-title, created_at 등 대응) )

apps/tests/serializers/test_deployment_serializers.py
=> test_deployment_serializer 253줄 obj -> submission으로 수정

apps/community/tests/comment_tests.py, apps/community/tests/test_comment.py, apps/community/views/user/comment_views.py
=> comment test 코드 작성

apps/community/tests/test_user_post.py, apps/community/urls.py
=> ♻️ refactor: url 중복 제거
